blank_issues_enabled: falce
contact_links:
  - name: Ask a Question
    url: https://github.com/Steve0Greatness/Clutter/discussions/new?category=q-a
    about: Post here if you need a question answered